on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src
          github_token: ${{ secrets.GITHUB_TOKEN }}
